<a href="https://colab.research.google.com/github/TaNuNian/Basicpython_ESANTH/blob/main/2_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


<img src = 'https://drive.google.com/uc?id=1prj-mqSRBDZ6j01TFDJGwcDniB-gqVE4' alt = 'image test' width ='1100px'>




บรรยายโดย <font color='blue'>ผู้ช่วยศาสตราจารย์ ดร.บุรัสกร นันทดิลก</font>

สาขาวิชา *Industrial Optimisation and Applications* (international program) และสาขาวิชา *คณิตศาสตร์*

คณะวิทยาศาสตร์ มหาวิทยาลัยแม่โจ้ จ.เชียงใหม่

คอร์สที่ 2 **Coding for Data scientists** ประกอบด้วย

2.1 <font color='darkpurple'>**Numpy**</font>

2.2 <font color='darkpurple'>Pandas</font>

2.3 <font color='darkpurple'>Matplotlib</font>

2.4 <font color='darkpurple'>Seaborn</font>

#**<font color='darkpurple'>2.1 Numpy**</font>

> **NumPy** เป็นไลบรารีของ Python ที่ให้โครงสร้างข้อมูลที่เรียบง่ายแต่ทรงพลัง นั่นคือ ใช้จัดการข้อมูล อาร์เรย์ n มิติ ได้

> การเรียนรู้ NumPy จะเป็นก้าวแรกในการเดินทางของนักวิทยาศาสตร์ข้อมูล (Python data scientist)

- Array
- Array Shapes and Axes
- Data Science Operations: Filter, Order, Aggregate

##<font color='blue'>2.1.1 Array</font>

> Array (อาเรย์) คือประเภทข้อมูลที่สามารถเก็บเรียงกันเป็นลำดับได้ หรือข้อมูลที่ระบุตำแหน่งได้

> อาจจะเรียงกันเป็นแถวแนวนอน เรียงกันเป็นเป็นแถวแนวตั้ง หรือเรียงกันเป็นตาราง หรือหลายๆตารางซ้อนกัน

<img src = 'https://drive.google.com/uc?id=1TBTrhNr7vb5Lkq9Z_mgt0x0FYRIeu7b-' alt = 'image test' width ='500px'>

In [ ]:
import numpy as np #เรียกใช้งาน numpy และแทนด้วย np

In [ ]:
number1D = np.array([1, 2, 3]) #ข้อมูลเรียงกันเป็นแถว (แนวนอน) ขนาด 1 แถว x 3 หลัก

In [ ]:
number1D

In [ ]:
number1D[2]

In [ ]:
number2D = np.array([ [1,2,3],
                      [4,5,6],
                      [7,8,9], ]) #ข้อมูลเรียงกันเป็นตารางขนาด 3 แถว x 3 หลัก

In [ ]:
number2D

In [ ]:
number2D[(2,2)]

In [ ]:
#สร้างตัวแปร text1 เพื่อเก็บข้อมูลตัวอักษร a, b, c ในแนวนอน
text1 = np.array(['a', 'b', 'c'])

In [ ]:
text1

In [ ]:
#สร้างตัวแปร text2 เพื่อเก็บข้อมูลตัวอักษร d, e, f ในแนวตั้ง
text2 = np.array([['d'],['e'],['f']])

In [ ]:
text2

In [ ]:
#ทดลองสร้างข้อมูล 3 มิติง่ายๆกันขนาด 2x3x4 กัน
# 2 ชั้น x 3 แถว x 4 หลัก
number3D = np.array([[[1, 2, 3, 4],
                      [11, 12, 13, 14],
                      [21, 22, 23, 24]],
                     [[34, 35, 36, 37],
                      [45, 46, 47, 48],
                      [56, 57, 58, 59]]])

In [ ]:
number3D

In [ ]:
number3D[(0,1,2)] # ทายซิ...ว่าเลขอะไร ??

[<font color='red'>**แบบฝึกหัด**</font>] จงสร้างอาเรย์ 2 มิติ เพื่อเก็บข้อมูลของวันที่ 1 และ 2 ไว้ในตัวแปร N1 และ N2 ตามลำดับ

และหาค่าเฉลี่ยของอุณหภูมิเฉลี่ยของทั้งสองวันเก็บไว้ใน N3

<img src = 'https://drive.google.com/uc?id=15NLul3WmoRXbOG8Bps0vqlcs9jLuRau3' alt = 'image test' width ='350px'>


In [ ]:
import numpy as np

In [ ]:
N1 = np.array([[23.5, 24.7, 25.1],
               [35.2 , 34.1 , 32.9]])

In [ ]:
N2 = np.array([[22.4,24.3,24.9],
               [37.1,35.5,34.6]])

In [ ]:
N3 = (N1 + N2)/2

In [ ]:
N3

array([[22.95, 24.5 , 25.  ],
       [36.15, 34.8 , 33.75]])

### ตัวอย่างการใช้งานอาเรย์ ในการปรับคะแนน

> การปรับคะแนน :สมมุติว่าคะแนนที่นักศึกษาได้ อาจจะน้อยกว่าที่คาดไว้ เพราะข้อสอบอาจจะยากเกินไป

> อาจารย์จะสามารถปรับเกรดง่ายๆได้ดังตัวอย่าง (คะแนนเต็ม = 100)



In [ ]:
import numpy as np

In [ ]:
scores = np.array([71, 36, 63, 87, 49, 74, 10])

In [ ]:
np.mean(scores) #คำนวณคะแนนเฉลี่ย

55.714285714285715

In [ ]:
CURVE_CENTER = 75 #ค่าที่ใช้ปรับค่าเฉลี่ย

In [ ]:
def adjust(scores):
  average = scores.mean()
  print('Average =', average)
  change = CURVE_CENTER - average
  print('Change =', change)
  new_scores = scores + change
  print('New scores=',new_scores)
  return np.clip(new_scores, scores, 100)

In [ ]:
adjust(scores)

Average = 55.714285714285715
Change = 19.285714285714285
New scores= [ 90.28571429  55.28571429  82.28571429 106.28571429  68.28571429
  93.28571429  29.28571429]


array([ 90.28571429,  55.28571429,  82.28571429, 100.        ,
        68.28571429,  93.28571429,  29.28571429])

##<font color='blue'>2.1.2 Array Shapes and Axes</font>


> อาร์เรย์ทั้งหมดมีคุณสมบัติที่เรียกว่า .shape ซึ่งส่งกลับค่าเป็นขนาดในแต่ละมิติ

> มิติของข้อมูลเป็นเท่าไร ไม่ใช่สิ่งสำคัญ  แต่สิ่งที่สำคัญจริงๆ คืออาร์เรย์ที่คุณส่งไปยังฟังก์ชันจะต้องมีรูปร่างตามที่ฟังก์ชันคาดหวัง

> วิธีทั่วไปในการยืนยันว่าข้อมูลมีรูปร่างที่เหมาะสมคือ การพิมพ์ข้อมูลและรูปร่างจนกว่าจะแน่ใจว่า ทุกอย่างทำงานได้ตามที่คาดหวัง

###1.) Shapes

> shape (รูปร่าง) บอกจำนวนชั้น/แถว/หลัก


<img src = 'https://drive.google.com/uc?id=1xKFEWL2SodhfYKONCqCmKP10qmGYQn--' alt = 'image test' width ='550px'>

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1, 2, 3, 4]) # 1d-array

In [ ]:
a1.shape

In [ ]:
a2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8]]) # 2d-array

In [ ]:
a2.shape

In [ ]:
a3 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8]],
               [[1, 2, 3, 4],
                [5, 6, 7, 8]],
               [[1, 2, 3, 4],
                [5, 6, 7, 8]]]) # 3d-array

In [ ]:
a3.shape

(3, 2, 4)

In [ ]:
temperatures = np.array([29.3, 42.1, 18.8, 16.1, 38.1, 12.0, 12.5, 48.7, 39.9, 33.1, 9.9, 22.3]).reshape(2,2,3)

In [ ]:
temperatures.shape

In [ ]:
temperatures #3d-array

In [ ]:
np.swapaxes(temperatures, 1, 2) #สลับระหว่าง แถว กับ หลัก

<font color='red'>16.1 เดิมอยู่ที่ตำแหน่ง (0,1,0) ย้ายไปอยู่ที่ตำแหน่ง (0,0,1)</font>

<font color='red'>39.9 เดิมอยู่ที่ตำแหน่ง (1,0,2) ย้ายไปอยู่ที่ตำแหน่ง (1,2,0)</font>


In [ ]:
np.swapaxes(temperatures, 0, 1) #สลับระหว่าง ชั้น กับ แถว

<font color='red'>16.1 เดิมอยู่ที่ตำแหน่ง (0,1,0) ย้ายไปอยู่ที่ตำแหน่ง (1,0,0)</font>

<font color='red'>39.9 เดิมอยู่ที่ตำแหน่ง (1,0,2) ย้ายไปอยู่ที่ตำแหน่ง (0,1,2)</font>

###2.) Axes
> axis (แกน)

<img src = 'https://drive.google.com/uc?id=1xKFEWL2SodhfYKONCqCmKP10qmGYQn--' alt = 'image test' width ='550px'>

In [ ]:
import numpy as np

In [ ]:
table1 =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]).reshape(4,4)

In [ ]:
table1

In [ ]:
table1.max()

In [ ]:
table1.max(axis=0)

In [ ]:
table1.max(axis=1)

In [ ]:
table2 =np.array([1, 2, 13, 14, 5, 6, 7, 8, 9, 10, 11, 12, 3, 4, 15, 16]).reshape(4,2,2)

In [ ]:
table2

In [ ]:
table2.max(axis=0)

In [ ]:
table2.max(axis=1)

In [ ]:
table2.max(axis=2)

[<font color='red'>**แบบฝึกหัด**</font>] จงสร้างอาเรย์ 3 มิติ ขนาด (2,3,2) เพื่อเก็บข้อมูล 1 - 12 ไว้ในตัวแปร num3d

และหาค่า min เมื่อ axis = 1

In [ ]:
import numpy as np

In [ ]:
num3d = np.array([[[1],[2],
                   [3],[4],
                   [5],[6]],
                  [[7],[8],
                   [9],[10],
                   [11],[12]]])

In [ ]:
num3d.min(axis=1)

array([[1],
       [7]])

In [ ]:
min = num3d.min(axis=1)

##<font color='blue'>2.1.3 Data Science Operations: Filter, Order, Aggregate</font>

> กรองข้อมูล, จัดเรียงข้อมูล, การนำข้อมูลมาต่อกัน

###1.) Masking

> การกรองข้อมูลโดยใช้ mask

> **mask** คือ อาเรย์ที่มีขนาดเท่ากันกับขนาดข้อมูลของเรา แต่ไม่ใช้อาเรย์ที่เก็บข้อมูล เป็นอาเรย์ที่เก็บค่า True หรือ False

เราสามารถใช้ mask เพื่อเป็น index ของข้อมูลได้ ซึ่ง*จะได้ค่าข้อมูลที่เป็น True ออกมา*


In [ ]:
import numpy as np

In [ ]:
np.linspace(0, 10, 25)

In [ ]:
np.linspace(0, 10, 25, dtype = int)

In [ ]:
numbers = np.linspace(5, 50 ,25, dtype = int).reshape(5,-1) #Reshaping an array with -1

In [ ]:
numbers

In [ ]:
mask = numbers % 5 == 0 #modulo

In [ ]:
mask

In [ ]:
numbers[mask]

In [ ]:
by_five = numbers[numbers % 5 == 0]

In [ ]:
by_five

In [ ]:
by_five.shape

###2.) Transposing

> การจัดเรียงข้อมูลโดยสลับแถวและหลัก

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [ ]:
a

In [ ]:
a.T

In [ ]:
a.transpose()

###3.) Sorting

> การจัดเรียงข้อมูลโดยเรียงลำดับข้อมูลจากน้อยไปหามาก

In [ ]:
import numpy as np

In [ ]:
data = np.array([[3, 1, 5],
                 [5, 7, 6],
                 [1, 8, 9]])

In [ ]:
data

In [ ]:
np.sort(data)

In [ ]:
data

In [ ]:
np.sort(data, axis = None)

In [ ]:
np.sort(data, axis = 0)

###4.) Concatenating

> การรวมข้อมูล หรือเอาข้อมูลมาต่อกัน

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2],
              [6, 7]])

In [ ]:
b = np.array([[3, 5],
              [8, 9]])

In [ ]:
np.hstack((a, b))

In [ ]:
np.vstack((a, b))

In [ ]:
np.vstack((b, a))

In [ ]:
np.concatenate((a, b))

In [ ]:
np.concatenate((a, b), axis = None)

[<font color='red'>**แบบฝึกหัด**</font>] จากภาพ จงนำข้อมูลของทั้ง 4 คน มาต่อกันและเรียงข้อมูลให้ถูกต้องตามเวลา

เมื่อกำหนดอาเรย์ T1, T2, T3, และ T4  แทนข้อมูลของคนที่ 1, 2, 3, และ 4 ตามลำดับ

<img src = 'https://drive.google.com/uc?id=1xxgkT7ctMkyivPRLbxzfA7HiDXzSLr-1' alt = 'image test' width ='550px'>

In [ ]:
import numpy as np

In [ ]:
#T1 =
#T2 =
#T3 =
#T4 =

In [ ]:
#T1324 = np.hstack()

In [ ]:
#T1324

In [ ]:
#TT = np.hstack()

In [ ]:
#TT

#**เอกสารอ้างอิง**

> https://www.programiz.com/python-programming/operators

> https://realpython.com/numpy-tutorial/

> https://www.geeksforgeeks.org/numpy-tutorial/

> https://www.w3schools.com/python/numpy/default.asp

> หรือค้นหาในเว็บเบราว์เซอร์ ด้วยคำว่า "Data Science, Numpy"

<img src = 'https://drive.google.com/uc?id=1yV9MzBC4w8J58eKhK8iCuo_O7ttjo4tQ' alt = 'image test' width ='1100px'>